### ISSUE TITLE
Don't use base64

### ISSUE THREAD

**Issue by kawa-kokosowa** [hypatia-software-org/staticfuzz#15]
route `/media/id` to a database lookup by id, returning either image or audio blob. You need to store image and audio binary in database.

**Comment by lillian-lemmer** [comment]
is store the data as binary blobs and then map database calls to a route like /media/idhere
damongant
yep, that's what I meant all along
lillian
thanks i didn't think of that
06:45 damongant
no base64 overhead, yay
