### ISSUE TITLE
Have text move autonomously

### ISSUE THREAD

**Issue by ix** [hypatia-software-org/staticfuzz#5]
For bonus points: don't use JS

**Comment by lillian-lemmer** [comment]
Done!

**Comment by kawa-kokosowa** [comment]
Could you elaborate?

**Comment by ix** [comment]
Hmm, I think you could create a good effect reminiscent of digital noise using CSS3 keyframes and altering the opacity, maybe having the text move left and right rapidly.

**Comment by kawa-kokosowa** [comment]
http://codepen.io/DirkWeber/pen/ArFvk This is very hackey, I guess this isn't something feasible for body copy...

But yes I do see what you're saying.

**Comment by ix** [comment]
That's pretty awesome, even better than what I had in mind. If it can be made at all efficient, I definitely think it'd fit right in.

**Comment by ix** [comment]
Might not be suitable for those with photosensitive epilepsy: http://codepen.io/anon/pen/XXVOvM

This is what I had in mind. The effect can be made more or less severe. Basically simulates the kind of blurring and lack of focus you'd get with CRTs.

**Comment by kawa-kokosowa** [comment]
Lain thats way cool and a great solution/implementation. Lets roll with
that.

**Comment by ix** [comment]
Neat. Not sure how efficient it is in larger bodies of text, but the settings are tweakable enough it should be scalable.

**Comment by kawa-kokosowa** [comment]
Should be fine
